version: '3.8'
services:
  giropops-senhas:
    image: pallestrelli/linuxtips-giropops-senhas:1.0
    container_name: giropops
    environment:
      - REDIS_HOST=redis
    ports:
      - "5000:5000"
    networks:
      - giropops
    depends_on:
      - redis
    
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 128M

  redis: 
    image: redis:alpine3.19
    networks:
      - giropops
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  giropops:
    driver: bridge